name: Production

on:
  push:
    branches: [production]

jobs:
  Transport:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Transporting
        env:
          DESTINATION: '${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:/root/www'
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "${{ env.DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ ${{ env.DESTINATION }}
            
  Boot-Container:
    name: Bootup Docker Container
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: cd /root/www && docker-compose up -d
