name: Production

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Transporting
        env:
          DESTINATION: '${{ secrets.USERNAME }}@${{ secrets.HOSTNAME }}:/var/root/www/wp-content/themes/base-theme'
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
        run: |
          echo "${{ env.DEPLOY_KEY }}" > deploy_key
          chmod 600 ./deploy_key
          rsync -chav --delete \
            -e 'ssh -i ./deploy_key -o StrictHostKeyChecking=no' \
            --exclude /deploy_key \
            --exclude /.git/ \
            --exclude /.github/ \
            --exclude /node_modules/ \
            ./ ${{ env.DESTINATION }}
