name: Production
on: [workflow_dispatch]

jobs:
  Build-And-Push:
    runs-on: ubuntu-latest
    steps:
      - name: Setting up machine & userspace emulator and virtualizer 
        uses: docker/setup-qemu-action@v1
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
        
      - name: Login to DockerHub
        uses: docker/login-action@v1 
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/wordpress-bootstrap-theme:latest
        
  Boot-Container:
    name: Deploy Build
    runs-on: ubuntu-latest
    steps:
      - name: starting docker container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOSTNAME }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.PORT }}
          script: cd /root/www && docker-compose up -d
